# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload-video
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="exemplo-de-audio.mp3"
Content-Type: audio/mpeg

< ./exemplo-de-audio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### 

# @name create-transcription
POST http://localhost:3333/videos/1d51c800-86ee-4841-a89a-c641feda4eed/transcription
Content-Type: application/json

{
    "prompt":"institucional, audio, corporation, produtos"
}

###
# @name generateAI
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId":"1d51c800-86ee-4841-a89a-c641feda4eed", 
    "temperature":1,
    "template":"Gere um resumo suscinto da transcrição do vídeo informado a seguir:'''{transcription}'''"
}